#ifndef P101_ERROR_PATH_WALK_CONSTANTS_H
#define P101_ERROR_PATH_WALK_CONSTANTS_H

#include <p101_env/env.h>

/* The shared p101 fault/logging variables are owned by lib_env; these are
 * local spellings of the one definition in <p101_env/env.h>. */
#define FAULT_CALL_ENV P101_ENV_FAULT_CALL_ENV
#define FAULT_ERRNO_ENV P101_ENV_FAULT_ERRNO_ENV
#define FAULT_LOG_ENV P101_ENV_FAULT_LOG_ENV
#define FAULT_NAME_ENV P101_ENV_FAULT_NAME_ENV
#define FAULT_MODE_ENV P101_ENV_FAULT_MODE_ENV
#define FAULT_AMOUNT_ENV P101_ENV_FAULT_AMOUNT_ENV
#define FAULT_REPEAT_ENV P101_ENV_FAULT_REPEAT_ENV
#define RESOURCE_LOG_ENV P101_ENV_RESOURCE_LOG_ENV
#define CALL_LOG_ENV P101_ENV_CALL_LOG_ENV
#define CALL_LOG_ARGS_ENV P101_ENV_CALL_LOG_ARGS_ENV
#define CALL_LOG_RESULT_ENV P101_ENV_CALL_LOG_RESULT_ENV

/* The child-side names are the inspect-capture launch protocol, not lib_env. */
#define CHILD_FAULT_CALL_ENV "P101_OBSERVE_CHILD_FAULT_CALL"
#define CHILD_FAULT_ERRNO_ENV "P101_OBSERVE_CHILD_FAULT_ERRNO"
#define CHILD_FAULT_LOG_ENV "P101_OBSERVE_CHILD_FAULT_LOG"
#define CHILD_FAULT_NAME_ENV "P101_OBSERVE_CHILD_FAULT_NAME"
#define CHILD_FAULT_MODE_ENV "P101_OBSERVE_CHILD_FAULT_MODE"
#define CHILD_FAULT_AMOUNT_ENV "P101_OBSERVE_CHILD_FAULT_AMOUNT"
#define CHILD_FAULT_REPEAT_ENV "P101_OBSERVE_CHILD_FAULT_REPEAT"
#define DEFAULT_RUN_PATH "p101-run.py"
#define DEFAULT_OBSERVE_PATH "inspect-capture"
#define DEFAULT_ANALYZE_PATH "p101-analyze.py"
#define DEFAULT_MODEL_PATH "p101-event-model"
#define RESOURCE_POLICY_SCHEMA "p101-resource-policy-findings-v1"
#define ANALYSIS_POLICY_SCHEMA "p101-analysis-findings-v1"
#define DEFAULT_LOG_PREFIX "/tmp/test-faults"

enum
{
    MSG_LEN                 = 256,
    FAULT_LEN               = 32,
    READ_BUF_LEN            = 4096,
    POLICY_INITIAL_CAPACITY = 4096,
    POLICY_OUTPUT_LIMIT     = 64 * 1024 * 1024,
    REPORT_FILE_MODE        = 0600,
    EXEC_FAILURE            = 127,
    DEFAULT_MAX_FAILURES    = 1024,
    MAX_FAILURES_LIMIT      = 100000,
    MAX_TOOL_ARGS           = 128,
    EXIT_FINDINGS           = 1,
    EXIT_TROUBLE            = 2
};

#endif    // P101_ERROR_PATH_WALK_CONSTANTS_H
